### PR TITLE
Moved nightscout code into separated folder

### PR DESCRIPTION
**Pull request by 3timeslazy**
Hi there,

First of all, thank you for your work. This script vastly improved my quality of life.

Secondly, in return I'd like to contribute to this project by adding support for the Nightscout V3 API. Prior to that, I wanted to slightly refactor the code to make it easy to work with two different versions and do not break anything else.

Current PR is the first of two I'm going to raise. Its goal is to prepare the code for the support of two versions without actual support for the new version. It includes:
- The common interfaces for both APIs
- The implementation for V1, which is basically the current logic, but behind `NightscoutAPI` interface
- Moved environment variables parsing into the `readConfig` function, to all the variables not be distributed across the index.ts file. For now the function only parses nightscout env, but I'm going to support the remaining ones in the subsequent PR

In the second PR I'm going to:
- add support for the Nightscout V3 API
- parse all the variables in the `readConfig`

I do so to make the review easier for you and me

Thank you in advance!

### CODE REVIEW

**Comment by timtheis** [comment]
I have discovered that Nightscout already has a built in capability to do this using connect.  (https://github.com/nightscout/nightscout-connect) Scroll down towards the bottom for Libre Link Up instructions.

Be sure to look at PR35 for a mod that fixes some problems with the current implementation, but has not been put into production yet. (https://github.com/nightscout/nightscout-connect/issues/35 )

**Comment by 3timeslazy** [comment]
@timtheis thank you for you suggestion! 

I've tried the `nightscout-connect` prior to raising this PR and frankly I didn't like it. It's nice to have it as a plugin embedded into the server, but it's not nice when the plugin crashes the whole server.

So, for now, I'd prefer to have it as a separate process running next to the server. I could have contributed to the nightscout itself but it's going to take much longer than patching the script I already know

**Comment by timtheis** [comment]
I understand your concern. I just wanted to be sure you were aware of
another possible solution. To date, connect linkup hasn’t crashed my
Nightscout server.

**Review by timoschlueter — APPROVED** [review]
Looks good to me! :)

**Comment by timoschlueter** [comment]
@3timeslazy I checked the PR. From my point of view it's ready to be merged. As you seem to have discovered the sidecar solution of nightscout-connect for your purpose, are you still working on implementing v3 based on your interface? :)

**Comment by 3timeslazy** [comment]
Hi @timoschlueter 

Sorry, I missed your messages. Sure, I’m going to finish my work. I see that the CI is falling, so as soon as I have time, I’ll check what’s falling, fix it and raise the second PR with the V3 implementation

**Pull request merged**
