### PR TITLE
add alpine base image

### PR DESCRIPTION
**Pull request by Gfeuillen**
Simply adding an alpine based image using multi-step build.

### CODE REVIEW

**Comment by timoschlueter** [comment]
Great idea! I am actually wondering if we should make this the default image since it is much smaller.
What do you think? :)

**Comment by Gfeuillen** [comment]
I can definitely do that if you want. The resulting image is indeed much smaller (so small it can run on a t3.nano along the nightscout instance ^^)

Want me to adapt the PR accordingly?

**Comment by timoschlueter** [comment]
@Gfeuillen: go ahead an make your image the new default. i think this would be a great improvement :)

**Comment by timoschlueter** [comment]
Closing this as stale.
The image size has been reduced with PR #136.

**Pull request closed without merging**
